name: seurat_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.2
  - r-seurat
  - r-tidyverse
  - r-patchwork
  - r-readr
  - r-data.table
  - r-cowplot
  - r-hdf5r
  - r-devtools
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - r-readr
  - r-tibble


